### ISSUE TITLE
 Bug: Codegen Incorrectly Uses `PydanticUndefined` Instead of `Undefined` in Pydantic Version < 2

### ISSUE THREAD

**Issue by freakaton** [zmievsa/cadwyn#129]
**Bug description**
I'm using `pydantic = "1.10.8"` and needed to create a migration with the addition of constraints.

I've used the [Addition of Constraints Recipe](https://docs.cadwyn.dev/recipes/#addition-or-narrowing-of-constraints) from the docs and created the migration:

Latest Schema:
```
class SendRequest(BaseModel):
    subject_text: str = Field(min_length=1)
```

Migration:
```
from pydantic.fields import Undefined
from cadwyn.structure import VersionChange, schema
from api.v1.schemas import SendRequest


class SubjectBodyTextAtLeast1Character(VersionChange):
    description = "Added constraint on min_length of subject_text"
    instructions_to_migrate_to_previous_version = [
        schema(SendRequest).field("subject_text").had(min_length=Undefined),
    ]
```

But, after I ran `generate_schemas.py`, codegen created the following schema:
```
class SendRequest(BaseModel):
    subject_text: str = Field(min_length=PydanticUndefined)
```

Despite using the first version of Pydantic, it incorrectly inserts a `PydanticUndefined` object, which is from the second version.

The generated schema file also lacks an import line for PydanticUndefined, so it fails with `NameError`:
```NameError: name 'PydanticUndefined' is not defined```

**Expected behavior**
I expect the generated schema to contain either `Field(min_length=Undefined)` or just `Field()` and no NameError exception.

**P.S.**
As a temporary workaround, I reworked my migration a bit and it helped:
```
class SubjectBodyTextAtLeast1Character(VersionChange):
    description = "Added constraint on min_length of subject_text"
    instructions_to_migrate_to_previous_version = [
        schema(SendRequest).field("subject_text").had(min_length=0),
    ]
```

**Comment by zmievsa** [comment]
Big thanks! I'll add it as a test.

On a side note:

* You used regular code blocks without a language specification: https://www.markdownguide.org/extended-syntax/#syntax-highlighting
* The naming of your migration could get a bit confusing. We have naming recommendations [here](https://docs.cadwyn.dev/reference/#versionchange__name__)
