### ISSUE TITLE
Version 3.4.5 introduced a breaking change

### ISSUE THREAD

**Issue by KonstantinVasilkov** [zmievsa/cadwyn#145]
**Bug Description:**

After updating Cadwyn to version 3.4.5, a GET endpoint that previously returned a 404 error with a custom message (when a business object was not found in the database) now returns a 500 error without any description. Despite configuring the endpoint to allow 404 responses, this change did not resolve the issue. Further investigation showed that the error was correctly generated and passed to the router.

**Expected Behavior:**

The endpoint should return a 404 error with the appropriate message if the business logic cannot find the specified business object in the database.

**Comment by zmievsa** [comment]
Fixed it in 3.5.0. Yanked 3.4.5. Big thanks for reporting this!
