### ISSUE TITLE
BUG: Cadwyn completely breaks `HTTPBearer` auth

### ISSUE THREAD

**Issue by isaacharrisholt** [zmievsa/cadwyn#147]
**Describe the bug**

Using `HTTPBearer` auth as a dependency completely breaks when using Cadwyn. The endpoints suddenly expect a `request` parameter to be passed in, and the dependency is not awaited.

**To Reproduce**

See example:

```python
from typing import Annotated
from fastapi import Depends, FastAPI, APIRouter
from .models.versions import version_bundle
from cadwyn import VersionedAPIRouter, Cadwyn
from fastapi.security.http import HTTPAuthorizationCredentials, HTTPBearer

# app = FastAPI()
# router = APIRouter()

app = Cadwyn(versions=version_bundle)
router = VersionedAPIRouter()

auth_header_scheme = HTTPBearer(description='Bearer token for authentication')


async def auth(
    auth_header: Annotated[
        HTTPAuthorizationCredentials | None,
        Depends(auth_header_scheme),
    ],
):
    print('auth', auth_header)


@router.get('/', dependencies=[Depends(auth)])
async def test():
    return 'Working'


# app.include_router(router)
app.generate_and_include_versioned_routers(router)
```

**Expected behavior**

HTTP bearer auth to work.

**Screenshots**

Here are the generated docs for the endpoint (ignore the different endpoint name):

![image](https://github.com/zmievsa/cadwyn/assets/47423046/14cd1f35-b490-4784-b85c-7902d98ead1f)

**Operating system**
 macOS

**Comment by zmievsa** [comment]
Verified that error exists and that it's not in verselect.

**Comment by isaacharrisholt** [comment]
Legend, thank you! Please let me know once this goes out

**Comment by isaacharrisholt** [comment]
Absolutely! I've got a couple of questions/suggestions, but I'll open some other issues :)

**Comment by isaacharrisholt** [comment]
@zmievsa this seems to work from an API perspective, but it breaks the `/docs` route - it no longer has the option to 'log in' like you would normally be able to with FastAPI, meaning you can't actually test any of the authenticated routes

**Comment by zmievsa** [comment]
![image](https://github.com/zmievsa/cadwyn/assets/17561586/233192bf-e371-49e6-96b8-7c8ba00c2f5e)

Never used this feature. Let me see how it got broken. Likely FastAPI has some hardcoded stuff as usual which breaks as a result of wrapping.

**Comment by zmievsa** [comment]
Found the issue. Fixing right now. Will fix within 2 hours, hopefully. This one should abolish the problem as a whole.

**Comment by isaacharrisholt** [comment]
> Found the issue. Fixing right now. Will fix within 2 hours, hopefully. This one should abolish the problem as a whole -- it really was hardcoded in FastAPI :(

Awesome, thank you for being so on it!

**Comment by zmievsa** [comment]
Please, take another look. This time it should be fine. Some use cases are still iffy but at least now I have covered all the known use cases with class-based dependencies.

**Comment by isaacharrisholt** [comment]
Looks like it's fixed :)
