### ISSUE TITLE
Redoc

### ISSUE THREAD

**Issue by isaacharrisholt** [zmievsa/cadwyn#153]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to use `redoc` as opposed to Swagger UI for docs, but Cadwyn doesn't seem to support it. The keyword argument is present, but it's hardcoded to `None`.

**Comment by zmievsa** [comment]
Yup. Would you like to add it into verselect?

**Comment by zmievsa** [comment]
This issue has inspired me to merge Cadwyn and verselect a little earlier than planned. Almost done. Will likely finish it later this week and will add redoc as a bonus.
