### ISSUE TITLE
Cadwyn does not properly handle swagger_ui_init_oauth and swagger_ui_oauth2_redirect_url arguments

### ISSUE THREAD

**Issue by gabloe** [zmievsa/cadwyn#175]
**Describe the bug**
After migrating my API to Cadwyn my OpenAPI docs UI no longer has the oauth OpenAPI properties mapped to the authorization dialog.

My API uses authorization code grant for protecting all routes. I am passing the below kwargs to Cadwyn. I see that cadwyn passes these along to FastAPI, but nevertheless my Swagger UI with Cadwyn is missing the pre-filled oauth fields when attempting interactive authorization.

        'swagger_ui_oauth2_redirect_url': settings.oauth.openapi_redirect_url,       # /oauth-redirect
        'swagger_ui_init_oauth': {
            "usePkceWithAuthorizationCodeGrant": True,
            "clientId": settings.oauth.openapi_client_id,                    # Azure client ID for my OpenAPI SPA
            "scopes": settings.oauth.scope_name,                             # Scope name, e.g.: user_impersonation
        },

If I switch back to using FastAPI instead of Cadwyn without changing anything else the issue goes away.

**To Reproduce**
1. Create a Cadwyn app using authorization code grant flow for oauth
2. Open /docs
3. Attempt to authorize
4. The expected client ID and pre-selected scopes are not set
5. Even if I fill in the correct client ID and scopes manually authorization fails because the redirect URI is not properly configured even though I have passed it to the constructor.

**Expected behavior**
I expect interactive authorization via the openapi docs endpoint works

**Additional context**
I am using FastAPI-Azure-OAuth for route security
https://intility.github.io/fastapi-azure-auth/

**Comment by zmievsa** [comment]
Thanks for reporting it! I'll take a look today!

**Comment by zmievsa** [comment]
@gabloe Please, try the latest version: https://pypi.org/project/cadwyn/3.15.1/

Ping me once you get a chance to test it 🙏

**Comment by gabloe** [comment]
Thanks @zmievsa! I tried it out, and that fixes the oauth issue, but now for some reason if I pass a lifespan to the constructor my Swagger page no longer loads.

With a lifespan I see only:
<img width="812" alt="image" src="https://github.com/zmievsa/cadwyn/assets/1381240/510f3500-ab7f-4205-a59e-33cac2a4467a">

If I don't pass a lifespan everything works except my initialization code that I want to run during app startup obviously cannot run.

**Comment by zmievsa** [comment]
Found the reason for this bug. I'll fix it and add it to my testcases today.

**Comment by zmievsa** [comment]
@gabloe Fixed it in 3.15.2. Already released.

**Comment by gabloe** [comment]
Thanks @zmievsa! I will try it out today

**Comment by gabloe** [comment]
Confirmed that it is working now. Thanks @zmievsa for the quick fixes!
