### ISSUE TITLE
Cadwyn breaks fastapi-pagination

### ISSUE THREAD

**Issue by gabloe** [zmievsa/cadwyn#183]
**Describe the bug**
[FastAPI-Pagination](https://uriyyo-fastapi-pagination.netlify.app/) injects dependencies in FastAPI routes to include query parameters for paginating response data. This does not appear to work with Cadwyn.

**To Reproduce**
1. Create a Cadwyn app.
2. Call add_pagination(app)
3. Create a route with a paginated response model
4. Call the route with curl or using the Swagger UI
5. Route will fail with RuntimeError("Use params, add_pagination or pagination_ctx")

**Expected behavior**
Routes with a paginated response model should have the injected pagination_ctx dependency.

**Comment by zmievsa** [comment]
Will take a look soon.

**Comment by zmievsa** [comment]
@gabloe Please, see 3.15.3 release. Should've fixed it. It fixed cardinality on starlette-exporter as well.

https://github.com/zmievsa/cadwyn/pull/187

**Comment by gabloe** [comment]
Thanks @zmievsa. Now the pagination_ctx dependency is added to the route, but the Swagger UI is not updated with the query params

**Comment by zmievsa** [comment]
@gabloe this results from the fact that fastapi-pagination edits the routes at the very end and we are not generating our swagger dynamically. Someone is already working on this issue though I am not sure about an ETA. 

As for a temporary workaround, Cadwyn apps have an "enrich_swagger" method that you can call after a call to fastapi-pagination to solve this issue.

Though I expect to solve the core issue rather soon.

**Comment by zmievsa** [comment]
Here is the issue I am referencing.
#164

**Comment by zmievsa** [comment]
Please, see 3.15.4. It should fix all the issues. I have tested it with fastapi-pagination too and it worked perfectly for me.

**Comment by gabloe** [comment]
Wonderful! It is working great for me :)

**Comment by zmievsa** [comment]
Thank you for your bug reports, @gabloe ! Very descriptive and helpful.
If you have any suggestions or need any further help -- feel free to contact me.
