### ISSUE TITLE
BackgroundTasks don't run

### ISSUE THREAD

**Issue by jfeaver** [zmievsa/cadwyn#212]
**Describe the bug**
`BackgroundTasks` don't run.

**To Reproduce**
Use this Cadwyn app:

```python
from cadwyn import Cadwyn, VersionBundle, HeadVersion, Version, VersionedAPIRouter
from fastapi import BackgroundTasks


def write_notification(email: str, message=""):
    with open("log.txt", mode="w") as email_file:
        content = f"notification for {email}: {message}"
        email_file.write(content)


router = VersionedAPIRouter()


@router.post("/send-notification/{email}")
async def send_notification(email: str, background_tasks: BackgroundTasks):
    background_tasks.add_task(write_notification, email, message="some notification")
    return {"message": "Notification sent in the background"}


app = Cadwyn(versions=VersionBundle(HeadVersion(), Version("2000-01-01")))
app.generate_and_include_versioned_routers(router)
```

1. Send a `POST` to the `/send-notification/{email}` route.
2. See that the expected message is returned ("Notification sent in the background").
3. Look for a log file from the background task. It isn't there.

**Expected behavior**
A log file should be created with the provided email param logged.

This vanilla FastAPI App has the expected behaviour:

```python
from fastapi import BackgroundTasks, FastAPI

app = FastAPI()

def write_notification(email: str, message=""):
    with open("log.txt", mode="w") as email_file:
        content = f"notification for {email}: {message}"
        email_file.write(content)

@app.post("/send-notification/{email}")
async def send_notification(email: str, background_tasks: BackgroundTasks):
    background_tasks.add_task(write_notification, email, message="some notification")
    return {"message": "Notification sent in the background"}
```

**Operating system**
MacOS 14.3.1 (23D60)

**Additional context**
cadwyn v4.2.3
fastapi v0.115.0

```
> poetry env info
Virtualenv
Python:         3.12.3
Implementation: CPython
Path:           /Users/nathan/Library/Caches/pypoetry/virtualenvs/example_background_task_bug--VJlo0R1-py3.12
Executable:     /Users/nathan/Library/Caches/pypoetry/virtualenvs/example_background_task_bug--VJlo0R1-py3.12/bin/python
Valid:          True

Base
Platform:   darwin
OS:         posix
Python:     3.12.3
Path:       /opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12
Executable: /opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/bin/python3.12
```

**Comment by zmievsa** [comment]
Thanks! I'll try to provide the fixes tomorrow!

**Comment by zmievsa** [comment]
Found the reason. Will publish the fix within 1-3 days.

**Comment by jfeaver** [comment]
Thanks for the updates!

**Comment by zmievsa** [comment]
@jfeaver please, check version 4.2.4  and see if it fixes your problem. I have also added a unit test for this behavior to make sure we never have such issues again.

**Comment by zmievsa** [comment]
@jfeaver thank you for publishing these bug reports! They really do help a lot.

If you have any extra feedback, any questions, or requests for Cadwyn -- feel free to ping me here or in our discord.

If you need any help integrating Cadwyn into your organization or consulting regarding API design/versioning -- feel free to contact me as well.
