### ISSUE TITLE
Improve FastAPI dependency management: Remove standard extras

### ISSUE THREAD

**Issue by bastienpo** [zmievsa/cadwyn#218]
**Is your feature request related to a problem? Please describe.**
FastAPI's standard extra installation includes extra dependencies specified by `fastapi = { version = ">=0.112.3", extras = ["standard"] }` in the _pyproject.toml_. This can lead to unnecessary dependencies when using alternative servers like **granian**. For example, **uvicorn[standard]**, **fastapi-cli**, **python-multipart**, and others are included but not always needed.

**Describe the solution you'd like**
1. Remove the "standard" extras from the default FastAPI installation.
2. Create a separate "tutorial" or "demo" extra that includes dependencies required for examples and documentation.
3. Add specific dependencies only where they are needed in the codebase or for testing purposes.

**Describe alternatives you've considered**
Create a "standard" extra for Cadwyn that mimics FastAPI's behavior.

**Additional context**
Dependency graph of **fastapi[standard] v0.115.0**:

```bash
cadwyn v4.2.4
    ├── fastapi[standard] v0.115.0
        ├── pydantic v2.9.2
        ├── starlette v0.38.6
        ├── typing-extensions v4.12.2
        ├── email-validator v2.2.0 (extra: standard)
        ├── fastapi-cli[standard] v0.0.5 (extra: standard)
        ├── httpx v0.27.2 (extra: standard)
        ├── jinja2 v3.1.4 (extra: standard)
        ├── python-multipart v0.0.10 (extra: standard)
        └── uvicorn[standard] v0.30.6 (extra: standard)
```

**Comment by bastienpo** [comment]
I'd be happy to contribute to this improvement if the maintainers agree with this approach.

**Comment by zmievsa** [comment]
Agreed. Let's do this!

**Comment by zmievsa** [comment]
Will review the changes today.

**Comment by zmievsa** [comment]
Thank you for your contribution!
