### ISSUE TITLE
`app.generate_and_include_versioned_routers` does not register routes

### ISSUE THREAD

**Issue by feluelle** [zmievsa/cadwyn#229]
**Describe the bug**

When calling `app.generate_and_include_versioned_routers` in Cadwyn `4.4.0` and beyond, it no longer registers the routes automatically. The same code (below) works for version `4.3.1`.

**To Reproduce**

1. Create a `main.py` file with the following content:
```python
from cadwyn import Cadwyn, HeadVersion, Version, VersionBundle, VersionedAPIRouter

app = Cadwyn(versions=VersionBundle(HeadVersion(), Version("2000-01-01")))

router = VersionedAPIRouter()

@router.get("/")
async def root():
    return {"message": "Hello World"}

app.generate_and_include_versioned_routers(router)

for version, router in app.router.versioned_routers.items():
    print("Version:", version)
    print("Routes:", router.routes)
```

2. Up on running this file via `fastapi dev main.py`, it prints empty routes.
```
Version: 2000-01-01
Routes: []
```

**Expected behavior**

I would expect this to print the routes it printed before `4.4.0`

```
Version: 2000-01-01
Routes: [Route(path='/openapi.json', name='openapi_jsons', methods=['GET', 'HEAD']), APIRoute(path='/', name='root', methods=['GET'])]
```

**Comment by feluelle** [comment]
> And in production, you would run your code using uvicorn or something similar which would produce the expected result: your routes will appear in your swagger.

Unfortunately, they don't. We run via uvicorn in production using `uvicorn.run()`.

**Comment by zmievsa** [comment]
Strange. I ran this code on the latest version and it worked:

```python
import uvicorn

from cadwyn import Cadwyn, HeadVersion, Version, VersionBundle, VersionedAPIRouter

app = Cadwyn(versions=VersionBundle(HeadVersion(), Version("2000-01-01")))

router = VersionedAPIRouter()


@router.get("/")
async def root():
    return {"message": "Hello World"}


app.generate_and_include_versioned_routers(router)

for version, router in app.router.versioned_routers.items():
    print("Version:", version)
    print("Routes:", router.routes)

uvicorn.run(app)

```

**Comment by feluelle** [comment]
And the 2nd use case is generating the open API docs, which basically calls the code from the example and then calls `get_open_api` from fastapi utils.

**Comment by zmievsa** [comment]
Understood. Then your best bet would be calling lifespan directly:

```python
from fastapi.openapi.utils import get_openapi
from httpx import AsyncClient
from fastapi.testclient import TestClient


with TestClient(app=app):
    for version, router in app.router.versioned_routers.items():
        openapi = get_openapi(..., routes=router.routes, ...)
```

This interface is public (unlike the one you use right now) and will be kept in the future versions of both Cadwyn and FastAPI.

**Comment by feluelle** [comment]
Yes, using `TestClient` to generate the docs works! Thank you. Let me check again why the uvicorn version doesn't work.

**Comment by feluelle** [comment]
I am getting a `RouteResponseBySchemaConverterDoesNotApplyToAnythingError` exception:
```
Response by response model converter \"...\" failed to find routes with the following response models: ['...']. This means that you are trying to apply this converter to non-existing endpoint(s).
```

**Comment by feluelle** [comment]
My `versions/__init__.py`:
```python
from datetime import date

from cadwyn.structure import HeadVersion, Version, VersionBundle

from models.versions.v2024_08_26 import (
    ...,
)

version_bundle = VersionBundle(
    HeadVersion(),
    Version(
        date(2024, 8, 26),
        ...,
    ),
    Version(date(2024, 6, 30)),
)
```
My `v2024_08_26.py`:
```python
from cadwyn import ResponseInfo, convert_response_to_previous_version_for
from cadwyn.structure import (
    VersionChange,
    endpoint,
)


class ...(VersionChange):
    instructions_to_migrate_to_previous_version = (
        endpoint(..., ["GET"]).had(response_model=...),
        endpoint(..., ["GET"]).had(response_model=...),
    )

    @convert_response_to_previous_version_for(...)
    def to_...(response: ResponseInfo) -> None:
        response.body = response.body["data"]
```

**Comment by zmievsa** [comment]
Can you replace them with some concrete names? They don't have to be your internal app names but it must be a code snippet that I can run to verify the issue

**Comment by feluelle** [comment]
I have updated the snippets.

**Comment by feluelle** [comment]
My `foo_router.py`:
```python
foo_router = VersionedAPIRouter(prefix="/api/v1")

@foo_router.get("/{bar_id}/foos")
async def get_bar_foos(...) -> PaginatedFooList:
  ...

@foo_router.get("/foos")
async def get_foos(...) -> PaginatedFooList:
  ...
```

**Comment by feluelle** [comment]
^This should be enough to reproduce it, I think.

**Comment by zmievsa** [comment]
Please, share them as a single code snippet. Otherwise, I need to make several assumptions when fixing them. I tried but the following works perfectly for me:

```python
from datetime import date

import uvicorn
from pydantic import BaseModel

from cadwyn import (
    Cadwyn,
    HeadVersion,
    ResponseInfo,
    Version,
    VersionBundle,
    VersionChange,
    VersionedAPIRouter,
    convert_response_to_previous_version_for,
    endpoint,
)


class Foo(BaseModel):
    foo: str


class PaginatedFooList(BaseModel):
    data: list[Foo]


class ChangePaginatedFooListToUnpaginatedFooList(VersionChange):
    description = ""
    instructions_to_migrate_to_previous_version = (
        endpoint("/api/v1/{bar_id}/foos", ["GET"]).had(response_model=list[Foo]),
        endpoint("/api/v1/foos", ["GET"]).had(response_model=list[Foo]),
    )

    @convert_response_to_previous_version_for(PaginatedFooList)
    def to_list_foo_response_model(response: ResponseInfo) -> None:
        response.body = response.body["data"]


version_bundle = VersionBundle(
    HeadVersion(),
    Version(date(2024, 8, 26), ChangePaginatedFooListToUnpaginatedFooList),
    Version(date(2024, 6, 30)),
)

foo_router = VersionedAPIRouter(prefix="/api/v1")


@foo_router.get("/{bar_id}/foos")
async def get_bar_foos(bar_id: str) -> PaginatedFooList: ...


@foo_router.get("/foos")
async def get_foos() -> PaginatedFooList: ...


app = Cadwyn(versions=version_bundle)
app.generate_and_include_versioned_routers(foo_router)

uvicorn.run(app)

```

**Comment by feluelle** [comment]
Yeah, I believe that has to do with our global (shared?) app initialization.
```python
app: Cadwyn

def build_app() -> Cadwyn:
    global app
    app = Cadwyn(
        title="Foo",
        lifespan=app_lifespan,
        versions=version_bundle,
    )
    match get_settings().mode:
        case AppMode.server:
            log.info("Running as server")
            app.generate_and_include_versioned_routers(foo_router)
        case AppMode.other_server:
            log.info("Running as other server")

    return app
```

I mean there are not many changes you have made since 4.3.1, right?

**Comment by zmievsa** [comment]
The main change was that we no longer do all of the "schema-generation" work during the call to `generate_and_include_versioned_routers`. Now we do this work in a lifespan which runs at startup by defaul. So you cannot conditionally include endpoints.

Why would you not want to include those endpoints for other server?

**Comment by feluelle** [comment]
Yes, then this is exactly what happens. 

> Why would you not want to include those endpoints for other server?

Why would I? It would expose unnecessary endpoints.

**Comment by zmievsa** [comment]
Hm... Then my strategy would probably be to use two different Cadwyn apps in such case

**Comment by feluelle** [comment]
Yeah, that would, unfortunately, require major refactoring, but probably you're right.

**Comment by zmievsa** [comment]
@feluelle Should we close the issue, then?

**Comment by feluelle** [comment]
Thank you very much for your help! :)

**Comment by zmievsa** [comment]
Always ready to help :)

**Comment by feluelle** [comment]
Since it was introduced in a minor release `4.4.0`, can we add a patch release (4.4.4) that would kind of "undo" that change, and we add this "breaking" logic to the `5.0.0` release instead?

**Comment by zmievsa** [comment]
> Since it was introduced in a minor release 4.4.0, can we add a patch release (4.4.4) that would kind of "undo" that change, and we add this "breaking" logic to the 5.0.0 release instead?

Sadly, we cannot really do that because webhooks logic depends on it. Sometimes even minor versions have small breaking changes (such as in python 3.13 or in zerover projects like FastAPI where any version can break anything).

> The function clearer doesn't do anymore what it supposed to do:
That is true. I will likely deprecate it and add another one with a clearer name once I figure out the better approach.

> Or at least give the user an option to keep using it the old way via a flag or so?
Hm... I never thought of your use case of using a single app for two different servers with different requirements, which is why it breaks your code. I am just not sure what such option would look like because Cadwyn's support of webhooks is tied to this logic.

If you describe your use case in more detail, I could either help you migrate to a supported approach (from the looks of it all you need to do is to pass a different version bundle into the other app and add all of the same routers except for the one you do not need) or add support for this approach in Cadwyn.
