### ISSUE TITLE
Nested pydantic models are not independently transformed

### ISSUE THREAD

**Issue by kurtmckee** [zmievsa/cadwyn#243]
## Problem description

My workplace often has nested pydantic models that are incorporated into other pydantic models, either as singular values or as lists of values.

For example:

```python
class Book(BaseModel):
    ...

class SeasonalDisplayResponse(BaseModel):
    featured_book: Book

class BookReservationsResponse(BaseModel):
    books: list[Book]
```

However, while putting together a tech demo for Cadwyn I'm finding that I have to write specific code for each response model (`SeasonalDisplayResponse` and `BookReservationsResponse`).

## Desired outcome

I'd like to be able to describe changes to the `Book` model once and have Cadwyn figure out that changes need to be applied to nested usages.

My preference would be to have an interface akin to:

```python
@convert_embedded_instance_to_previous_version_for(Book)
def downgrade_to_older_key_name(some_object):
    some_object.body["due_on"] = some_object.body("due_date")
```

In the tech demo I'm working on, it's certainly feasible to write near-identical converters for the two response models, but the case for Cadwyn will be strengthened by supporting single-source changes as described here.

Thoughts?

**Comment by zmievsa** [comment]
I am worried that the amount of magic here will be overwhelming to a regular user. The list case is simple and straightforward but the nested models case can cause a lot more confusion.

Migration-based versioning is one of the most involved kinds of versioning: we sacrifice simplicity and isolation of versions for maximum possible ease of maintenance. So any other step towards complexity will make it even tougher to understand. Here's a model I have in my head: we fundamentally write converters for **endpoints**, not models, and the schema argument is just a convenient shortcut for similar groups of endpoints. This is exactly how every other migration-based framework works -- including Stripe's.

You can still reach better code reuse by just writing the converter for `Book` as a function above the version changes and applying it.

So I guess this kind of change would be a step in the wrong direction. What do you think?

**Comment by kurtmckee** [comment]
I'm sympathetic to the "magic is inscrutable" argument! I'm also motivated by my use case.

I'm currently tasked with exploring JSON:API for the org to potentially standardize on. JSON:API constrains the request and response JSON shapes to put everything in a top-level `data` key. I'm anticipating that response classes are going to all look like:

```python
class GetBookResponse(BaseModel):
    data: Book

class GetReservedBooksResponse(BaseModel):
    data: list[Book]
```

This effectively means that every response class is merely an envelope, and every route will have to be touched if the `Book` schema evolves. It's in this context that I'm very interested in being able to convert nested pydantic models.

If you're open to me exploring this, I'll work to cook up some test cases and a PR to address those test cases.

It's also okay to say "no"! I just want to confirm you're open to reviewing a PR if I'm able to put that together in a sane way.

**Comment by zmievsa** [comment]
Thanks for describing your use case! I've thought about it for quite a bit more and I think I am ready to say that it is better to just write a migrator function for every endpoint that you are trying to migrate, even if it results in some code duplication.

So let's not pursue this solution for now

**Comment by kurtmckee** [comment]
I appreciate the consideration! I'll close this issue.
