### ISSUE TITLE
Add a test that checks whether `Literal` in route dependencies gets migrated as expected

### ISSUE THREAD

**Issue by zmievsa** [zmievsa/cadwyn#25]
For example, let's say `Literal` has enum values as its args. Will we migrate them to older versions of the same enum when generating new routes?  I don't think so.

**Comment by Aditi840** [comment]
@Ovsyanka83, can I work on this one, just give me an overview on what needs to be done.

**Comment by Ovsyanka83** [comment]
Let's say we have a versioned enum such as [this one](https://github.com/Ovsyanka83/universi/blob/main/tests/_data/latest/__init__.py#L12). Let's say we used as a type in some schema (e.g. [discriminators](https://docs.pydantic.dev/1.10/usage/types/#nested-discriminated-unions)). If we [delete](https://github.com/Ovsyanka83/universi#removing-enum-members) the value from that enum, what happens to the schema? We need some way to check that.

So we need a test that checks what's going on and we need a sane error message to be displayed to the user once they get into this situation.

**Comment by Aditi840** [comment]
@Ovsyanka83, will you see my pull request.

**Comment by Ovsyanka83** [comment]
I'll be sure to take a look at it tomorrow.
