### ISSUE TITLE
Collect changelog from migrations

### ISSUE THREAD

**Issue by emilskra** [zmievsa/cadwyn#43]
Add `VersionBundle.generate_changelog(self)` that will output a list of versions and changelog for each of them. Here's the proposed format for it:

```json
[
    {
        "version": "2022-11-16",
        "changelog": []
    },
    {
        "version": "2023-04-12",
        "changelog": [
            {
                "description": "Change `POST /v1/users` status code to 201 instead of 200",
                "side_effects": false,
                "endpoint_changes": [
                    {
                        "type": "endpoint.had",
                        "method": "POST",
                        "path": "/v1/users"
                    }
                ],
                "schema_changes": [
                    {
                        "type": "schema.field.had"
                        // More stuff here
                    }
                ]
            }
        ]
    }
]
```

We could also unite all changes into the same polymorphic payload but I'm still questioning whether that's a good idea.

**Comment by Ovsyanka83** [comment]
@emilskra Let's split it into two tasks and put it under a milestone.

The whole task can become a milestone that contains two tasks: make changelog in some format such as json as the first task and put to swagger as a second task. WDYT?

**Comment by Ovsyanka83** [comment]
It needs to be collected from the entire VersionBundle into some simple format such as JSON so that it can be transferred anywhere.

I believe that making it a method on the VersionBundle makes sense such as `def changelog(self)`
