### ISSUE TITLE
Add support for getting different versions of objects based on current API version

### ISSUE THREAD

**Issue by zmievsa** [zmievsa/cadwyn#6]
**Is your feature request related to a problem? Please describe.**
Often things like error messages and status codes are also versioned. We want some solution that allows us get a different variable in business logic based on the current API version.

**Describe the solution you'd like**
The following will allow us to preserve the type hints on the module and return the correct version of the value in runtime.

Based on #5 

```python
from cadwyn import get_current_version
from versioned_dir.unions import errors

async def my_business_logic():
    raise get_current_version(errors).DOES_NOT_EXIST_ERROR
```

However, it feels like something that could be abused to add side effects to migrations without side effects like so:

```python
from cadwyn import get_current_version
from versioned_dir.unions import weird_module

async def my_business_logic():
    if get_current_version(weird_module).raise_err:
        raise Exception
```

So now we have side effects in a version that didn't have any side effects. To solve this, we could:

* disallow using module().variable() syntax in version changes without side effects
* disallow module().variable() syntax altogether and force people to do side effects with "if-s"

NOTE: Make sure that user uses unions. Also, it might be a good idea to make it a method of VersionBundle so that a single service could have multiple packages like this

**Comment by Ovsyanka83** [comment]
This makes a lot more sense than I thought.

For example, if service uses external connectors, we add a separate module for their definitions: "external_connectors.py" and edit them in migrations every time we start using a different version of API of others.

**Comment by zmievsa** [comment]
I thought about it once again: this is a bad idea. Instead, if-statements with side effects are a much safer choice.

This functionality would render side effect detection useless and will significantly complicate tests of business code so its value is not enough to justify its complexity.

Connectors should be picked with if-statements to make sure that we can measure coverage on them.
